language: node_js
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
addons:
after_success:
  - npm run coverage
after_script:
  - cat coverage/lcov.info | ./node_modules/codeclimate-test-reporter/bin/codeclimate.js
  - cat coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
notifications:
  slack: paviateam:C1q99hL9XXpiPpau2PUrVZPC